# Generated by Django 3.0.7 on 2020-06-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0002_auto_20200610_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
