# Generated by Django 3.0.7 on 2020-06-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.BigIntegerField(),
        ),
    ]
