# Generated by Django 3.0.7 on 2020-06-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0002_auto_20200618_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='descricao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
