# Generated by Django 3.0.7 on 2020-06-10 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Salada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('dtColheita', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('origem', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.BigIntegerField()),
                ('valorCalorico', models.BigIntegerField()),
                ('opcoes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evolucaoComida.Opcao')),
                ('salada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evolucaoComida.Salada')),
                ('tipoComida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evolucaoComida.Tipo')),
            ],
        ),
    ]
